import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {cleanTelegramHtml,postSchema,scheduledUtc,renderTemplate} from '../src/features/telegram/content';
import {encryptSecret,decryptSecret} from '../src/features/telegram/crypto';
const db=new PGlite();const admin='00000000-0000-4000-8000-000000000001';let chat:string;
before(async()=>{await db.exec(`create schema auth; create role anon nologin; create role authenticated nologin; create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await db.exec(await readFile('supabase/migrations/202609070001_crm.sql','utf8'));await db.exec(await readFile('supabase/migrations/202609070002_telegram.sql','utf8'));await db.exec(`insert into auth.users values('${admin}');insert into profiles values('${admin}','Admin','admin');`);chat=(await db.query<{id:string}>("insert into telegram_chats(chat_id,title) values('-10011111','School') returning id")).rows[0].id;});
after(()=>db.close());
async function save(when:string|null,draft=false){return(await db.query<{id:string}>('select telegram_save_post($1,$2,$3,$4,$5,$6,$7,$8,$9) id',[null,admin,'<b>Hello</b>',[],[],[chat],when,'Europe/Kyiv',draft])).rows[0].id;}
test('Telegram secrets encrypted with authenticated encryption; wrong keys/tampering fail',()=>{const key=randomBytes(32).toString('base64'),secret='sensitive-session';const encrypted=encryptSecret(secret,key);assert.ok(!encrypted.includes(secret));assert.equal(decryptSecret(encrypted,key),secret);assert.notEqual(encrypted,encryptSecret(secret,key));assert.throws(()=>decryptSecret(encrypted,randomBytes(32).toString('base64')));assert.throws(()=>decryptSecret(encrypted.slice(0,-5)+'abcde',key));});
test('rich content strips scripts, unsafe links and template injections',()=>{const clean=cleanTelegramHtml('<b>Hello</b><script>token()</script><a href="javascript:alert(1)">Bad</a><img src=x onerror=alert(1)>');assert.ok(clean.includes('<b>Hello</b>'));assert.ok(!clean.includes('script'));assert.ok(!clean.includes('javascript'));assert.ok(!clean.includes('onerror'));assert.equal(renderTemplate('{{child_name}}',{child_name:'<script>x</script>'}),'&lt;script&gt;x&lt;/script&gt;');});
test('timezone schedules reject DST gaps, ambiguous clocks and past time',()=>{assert.throws(()=>scheduledUtc('2027-03-28T03:30','Europe/Kyiv'),/не існує/);assert.throws(()=>scheduledUtc('2027-10-31T03:30','Europe/Kyiv'),/повторюється/);assert.throws(()=>scheduledUtc('2020-01-01T12:00','UTC'),/майбутньому/);assert.ok(scheduledUtc('2030-06-01T18:00','Europe/Kyiv').startsWith('2030-06-01T15:00'));});
test('album/buttons and caption limits are checked before enqueue',()=>{const base={body:'Hello',destinations:[crypto.randomUUID()],media:[{url:'https://example.com/a.png',kind:'photo',name:'a'},{url:'https://example.com/b.png',kind:'photo',name:'b'}],buttons:[{label:'Join',url:'https://example.com'}],mode:'now',localTime:'',timezone:'UTC'};assert.equal(postSchema.safeParse(base).success,false);assert.equal(postSchema.safeParse({...base,buttons:[]}).success,true);assert.equal(postSchema.safeParse({...base,buttons:[],body:'a'.repeat(1025)}).success,false);});
test('staff can read Telegram state but cannot access secrets or inject scheduled posts',async()=>{await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${admin}',false)`);try{assert.equal((await db.query('select * from telegram_chats')).rows.length,1);await assert.rejects(db.query('select * from telegram_credentials'),/permission denied/);await assert.rejects(db.query("insert into telegram_posts(body) values('Injected')"),/permission denied/);await assert.rejects(db.query('select telegram_claim_delivery(null)'),/permission denied/);}finally{await db.exec('reset role');}});
test('only due posts are claimed, delivery is claimed once and cancellation cannot overtake publishing',async()=>{const draft=await save(null,true);const future=await save('2035-01-01T00:00:00Z');assert.equal((await db.query<{d:null}>('select telegram_claim_delivery($1) d',[draft])).rows[0].d,null);assert.equal((await db.query<{d:null}>('select telegram_claim_delivery($1) d',[future])).rows[0].d,null);const due=await save('2020-01-01T00:00:00Z');const first=await db.query<{d:{id:string}}>('select telegram_claim_delivery($1) d',[due]);assert.ok(first.rows[0].d.id);assert.equal((await db.query<{d:null}>('select telegram_claim_delivery($1) d',[due])).rows[0].d,null);await assert.rejects(db.query('select telegram_cancel_post($1,$2)',[due,admin]),/розпочато/);await db.query('select telegram_cancel_post($1,$2)',[future,admin]);assert.equal((await db.query<{status:string}>('select status from telegram_posts where id=$1',[future])).rows[0].status,'Cancelled');});
test('archived destination is not sent and saving audience is atomic on invalid recipient',async()=>{const id=await save('2020-01-01T00:00:00Z');await db.query("update telegram_chats set status='archived' where id=$1",[chat]);assert.equal((await db.query<{d:null}>('select telegram_claim_delivery($1) d',[id])).rows[0].d,null);assert.equal((await db.query<{status:string}>('select status from telegram_deliveries where post_id=$1',[id])).rows[0].status,'failed');const before=(await db.query('select * from telegram_posts')).rows.length;await assert.rejects(save('2020-01-01T00:00:00Z'),/неактивний/);assert.equal((await db.query('select * from telegram_posts')).rows.length,before);});
